### ISSUE TITLE
Enable students to view grades

### ISSUE THREAD

**Issue by kbedoway** [kbedoway/github_flow_repo#1]
**User Story:**
As a student, I would like to be able to view my grades for individual assignments and the overall class so that I can keep with with my progress and not worry about receiving hand-graded papers.

* Persona: Students who need to view current grades
* Feature: Students view grades online
* Business value: Grades will be stored even if paper records are lost; students can conveniently view grades

**Tasks:**
- [ ] Make sure database schemes handle grade updates
- [ ] Create HTML views for viewing grades
- [ ] Connect HTML views to database/backend to complete function

**Acceptance Criteria:**
1. Only works for current semester

**Acceptance Tests:**
1. Students should be able to view their posted and missing grades
2. Students should not be able to view their unposted grades
3. Students should only be able to see their grades
4. Students should be able to test hypothetical grades
