### ISSUE TITLE
Enable quit option

### ISSUE THREAD

**Issue by kbedoway** [kbedoway/github_flow_repo#4]
**User Story:**
As a user, I would like to be able to exit the program when I type q, this way there is only one way to exit the program and I will know if I have done so successfully.

* Persona: Users of program
* Feature: Users can exit program
* Business value: There is only one way to exit the program

**Tasks:**
- [ ] Add q to menu
- [ ] Make sure q works to quit
- [ ] Make sure inputs other than q and other menu options lead to invalid message and prompt again

**Acceptance Criteria:**
1. Only works for this program

**Acceptance Tests:**
1. Users should be able to type q to exit the program
2. Users should not be able to type inputs other than q and other menu options
