### ISSUE TITLE
Enable search movie names option

### ISSUE THREAD

**Issue by kbedoway** [kbedoway/github_flow_repo#5]
**User Story:**
As a user, I would like to be able to search movie names when I type sn, this way there is only one way to search movie names and I will know if I have done so successfully.

* Persona: Users of program
* Feature: Users can search movie names
* Business value: There is only one way to search movie names

**Tasks:**
- [ ] Add sn to menu
- [ ] Make sure sn works to search movie names
- [ ] Make sure inputs other than sn and other menu options lead to invalid message and prompt again

**Acceptance Criteria:**
1. Only works for this program

**Acceptance Tests:**
1. Users should be able to type sn to search movie names
2. Users should not be able to type inputs other than sn and other menu options
