### ISSUE TITLE
Enable search cast members option

### ISSUE THREAD

**Issue by kbedoway** [kbedoway/github_flow_repo#6]
**User Story:**
As a user, I would like to be able to search cast members when I type sc, this way there is only one way to search movie names and I will know if I have done so successfully.

* Persona: Users of program
* Feature: Users can search cast members
* Business value: There is only one way to search cast members

**Tasks:**
- [ ] Add sc to menu
- [ ] Make sure sc works to search cast members
- [ ] Make sure inputs other than sc and other menu options lead to invalid message and prompt again

**Acceptance Criteria:**
1. Only works for this program

**Acceptance Tests:**
1. Users should be able to type sc to search cast members
2. Users should not be able to type inputs other than sc and other menu options
