### ISSUE TITLE
Enable list all movies option

### ISSUE THREAD

**Issue by kbedoway** [kbedoway/github_flow_repo#7]
**User Story:**
As a user, I would like to be able to list all movie names when I type list, this way there is only one way to list all movie names and I will know if I have done so successfully.

* Persona: Users of program
* Feature: Users can list all movie names
* Business value: There is only one way to list all movie names

**Tasks:**
- [ ] Add list to menu
- [ ] Make sure list works to list all movie names
- [ ] Make sure inputs other than list and other menu options lead to invalid message and prompt again

**Acceptance Criteria:**
1. Only works for this program

**Acceptance Tests:**
1. Users should be able to type list to list all movie names
2. Users should not be able to type inputs other than list and other menu options
